options(repos = c(CRAN = "https://cran.rstudio.com/"))
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("readr")) install.packages("readr")
if (!require("ggplot2")) install.packages("ggplot2")
if (!require("here")) install.packages("here")

library(tidyverse)
library(readr)
library(ggplot2)
library(here)

# Set working directory to the project root
setwd(here())

# Find all 'improvement.csv' files in subdirectories under 'Data-Analysis'
improvement_files <- list.files(path = here("Data-Analysis"), pattern = "improvement.csv", recursive = TRUE, full.names = TRUE)

# Extract the list of subdirectories under 'Data-Analysis'
sub_dirs <- list.dirs(path = here("Data-Analysis"), recursive = FALSE, full.names = TRUE)

# Extract the subject names from the directories
subject_names <- basename(sub_dirs)

# Map subject names to the improvement files
subject_files <- tibble(filepath = improvement_files) %>%
  mutate(subject = map_chr(filepath, function(x) {
    subdir <- dirname(x)
    subject <- basename(subdir)
    return(subject)
  }))

# Print out unique subjects to confirm correct extraction
print(unique(subject_files$subject))
# Read data and add a column to identify the subject or subfolder
improvements <- map_df(subject_files$filepath, read_csv, .id = "subject") %>%
  mutate(subject = subject_files$subject[as.integer(subject)])

# Split the data by metric and sizes and generate plots
metrics <- unique(improvements$Metric)
size_categories <- unique(improvements$SIZE_CATEGORY)
# Create and save plots for each metric
plots <- lapply(metrics, function(metric) {
  data_subset <- filter(improvements, Metric == metric)
  
  plot <- ggplot(data_subset, aes(x = subject, y = Improvement, fill = SIZE_CATEGORY)) +
    geom_bar(stat = "identity", position = position_dodge(), width = 0.7) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
    theme_minimal(base_size = 12) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          plot.background = element_rect(fill = "white"),
          panel.background = element_rect(fill = "white")) +
    labs(title = paste("Improvement in", metric, "across subjects"),
         x = "Subject",
         y = "Improvement (%)",
         fill = "Size Category") +
    facet_wrap(~ Comparison, scales = "free_y")+  # Separate plots by comparison type with free y scales
    scale_y_continuous(limits = c(-300, 100), breaks = c(seq(-150, 0, by = 50),seq(0, 100, by = 20)))
  # Save the plot
  ggsave(filename = here("Data-Analysis", "output", paste0("Improvement_", metric, ".png")), plot = plot, width = 10, height = 8, units = "in", bg="white")
})

# Calculate meaian improvements by metric and comparison
mean_improvements <- improvements %>%
  group_by(Metric, Comparison, SIZE_CATEGORY) %>%
  summarize(Mean_Improvement = mean(Improvement, na.rm = TRUE), .groups = 'drop')
print("checking the data:")
print(mean_improvements,n=150)  # Check the aggregated data
# Define the colors for each comparison type
comparison_types <- unique(mean_improvements$Comparison)
colors <- c("codon_cpp" = "lightblue", "codon_python" = "lightgreen")


  

# Create and save bar plots for mean improvements by metric and size category
bar_plots <- lapply(size_categories, function(size_category) {
  data_subset <- filter(mean_improvements, SIZE_CATEGORY == size_category)
# Modify the data_subset to adjust the improvement value visually
data_subset <- mutate(data_subset, Visible_Improvement = ifelse(Metric == "cpu_usage" & Comparison == "codon_python" & size_category=="small", -0.5, Mean_Improvement))
  

  if (size_category == "large") {
    y_limits <- c(-320, 100)
    breaks_custom <- c(seq(-320, 0, by = 50), seq(0, 100, by = 20))
  } else if (size_category == "medium") {
    y_limits <- c(-300, 100)
    breaks_custom <- c(seq(-300, 0, by = 50), seq(0, 100, by = 20))
  } else if (size_category == "small") {
    y_limits <- c(-300, 100)
   breaks_custom <- c(seq(-300,0, by = 50), seq(0, 100, by = 20))
  }
  plot <- ggplot(data_subset, aes(x = Metric, y = Visible_Improvement, fill = Comparison)) +
    geom_bar(stat = "identity", position = position_dodge(), width = 0.7) +
    scale_fill_manual(values = colors) +
    labs(title = paste("Mean Improvement Percentage by Metric for", size_category, "size"),
         x = "Metric",
         y = "Mean Improvement (%)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_y_continuous(limits = y_limits, breaks = breaks_custom)+
   geom_text(data = subset(data_subset, Visible_Improvement == -0.5),
              aes(label = paste(Comparison, sprintf("%.2f%%", Mean_Improvement), sep = ": ")), vjust = -0.5, color = "black", position = position_dodge(width = 1))
  #  guides(fill = FALSE)  # This line removes the legend for fill colors


  # Save the plot
  ggsave(filename = here("Data-Analysis", "output", paste0("Mean_Improvement_Plot_", size_category, ".png")), plot, width = 10, height = 8, units = "in", bg = "white")
})

# Calculate mean improvements by metric and comparison
mean_improvements <- improvements %>%
  group_by(Metric, Comparison, SIZE_CATEGORY) %>%
  summarize(Mean_Improvement = mean(Improvement, na.rm = TRUE), .groups = 'drop') %>%
  mutate(Color_Label = paste(Comparison, SIZE_CATEGORY, sep = "_"))  # Creating color labels for aesthetics

# Define colors for the combinations of comparisons and size categories
colors_cpp <- c("codon_cpp_small" = "red", "codon_cpp_medium" = "blue", "codon_cpp_large" = "green")
colors_python <- c("codon_python_small" = "red", "codon_python_medium" = "blue", "codon_python_large" = "green")

# Function to create and save a bubble chart for a given comparison type
create_and_save_bubble_chart <- function(data, comparison_type, colors) {
  bubble_chart <- ggplot(data, aes(x = Metric, y = Mean_Improvement, size = abs(Mean_Improvement), color = Color_Label)) +
    geom_point(alpha = 0.5) +
    scale_size_continuous(range = c(5, 20), guide = FALSE) +
    scale_color_manual(values = colors) +
    labs(title = paste("Mean Improvements for", comparison_type, "Across Metrics and Sizes"),
         x = "Metric", y = "Mean Improvement (%)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "bottom")

  # Save the plot in the specified output directory
  output_path <- here("Data-Analysis", "output")
  if (!dir.exists(output_path)) {
    dir.create(output_path, recursive = TRUE)
  }
  ggsave(filename = file.path(output_path, paste("Mean_Improvement_Bubble_Chart_", comparison_type, ".png", sep = "")), plot = bubble_chart, width = 12, height = 8, units = "in", dpi = 300, bg = "white")
}

# Filter and create bubble chart for CPP comparisons
improvements_cpp <- filter(mean_improvements, str_detect(Comparison, "cpp"))
create_and_save_bubble_chart(improvements_cpp, "CPP", colors_cpp)

# Filter and create bubble chart for Python comparisons
improvements_python <- filter(mean_improvements, str_detect(Comparison, "python"))
create_and_save_bubble_chart(improvements_python, "Python", colors_python)
